#!/bin/sh

function last_char() {

	last_character="$(printf "%s" "$1" | tail -c 1)"

	echo "$last_character"
}

function bp() {

	if [ "list" = "$1" ] || [ "l" = "$1" ] || [ "" = "$1" ]; then

		printf "\t ________________________________\n"
		printf "\t| Currently available wallpapers |\n"
		printf "\t --------------------------------\n"
		ls -1 "$BGDIR" | cut -f 1 -d '.' | sed -r 's/^(.*)$/\t|\1/'
		printf "\t --------------------------------\n"

		exit 0
	fi

	IMG=$(find "$BGDIR" -name "$1*" -print | tail -n 1)

	if test -d "$IMG"; then

		if [ "list" = "$2" ] || [ "l" = "$2" ] || [ "" = "$2" ]; then
			printf "\t ___________________________________\n"
			printf "\t| Available wallpapers in '$IMG' |\n"
			printf "\t -----------------------------------\n"
			ls -1 "$IMG" | cut -f 1 -d '.' | sed -r "s/^(.*)\$/\t|\\1/"
			printf "\t --------------------------------\n"

			exit 1
		fi

		BGDIR="$IMG"
		IMG=$(find "$BGDIR" -name "$2*" -print | tail -n 1)
	fi

	if ! test -z "$IMG" && ! [ "$BGDIR" = "$IMG" ] ; then

		if command -v feh > /dev/null; then
			feh --bg-scale $IMG
		elif command -v hsetroot > /dev/null; then
			hsetroot -extend $IMG
		else
			echo "[ERROR]   Can't find Feh/Hsetroot, try running setup first"

			exit 1
		fi

	else
		echo "[ERROR]   No matches to provided image: '$1*'"

		exit 1
	fi
}
BGDIR='/home/tortea/Wallpapers/' bp $@
